Features
energytoolbase/volumerize pull request #1
Opened 2021-01-13 16:20 UTC by jjedd97

Add influx, redis and trickle to volumerize. Add a script to help with backups.

2021-01-15 23:21 UTC, NunchakusLei requested changes

2021-01-15 23:21 UTC, NunchakusLei commented on database_backup.sh
> + dir="/source1/"
It will be better if this is not hard coded. Can it refer to something like `VOLUMERIZE_SOURCE1`?

2021-01-15 23:21 UTC, NunchakusLei commented on Dockerfile
> +      libtool \
Are those package needed on runtime? If not, we can probably remove them in the Cleanup section below. Will need to test out. 

Removing them could help to make the image size smaller.

2021-01-18 16:30 UTC, jjedd97 commented on Dockerfile
> +      libtool \
libtirpc-dev seems to be the only one required

2021-01-18 16:59 UTC, NunchakusLei approved these changes

2021-01-18 16:59 UTC, merged